# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simplesshkey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userkey',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userkey',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='userkey',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userkey',
            name='last_used',
        ),
    ]
