# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplesshkey', '0002_auto_20170611_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='keytype',
            field=models.CharField(blank=True, help_text="Type of key, e.g. 'ssh-rsa'", max_length=32),
        ),
    ]
