# Generated by Django 4.2.23 on 2025-06-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplesshkey', '0004_auto_20180325_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='keytype',
            field=models.CharField(blank=True, help_text="Type of key, e.g. 'ssh-rsa'", max_length=512),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
